// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrA4TpUuZpIcLq9vkuU_V89dGWmzROznM',
    appId: '1:620715294422:web:e2d33124aa0767366e1377',
    messagingSenderId: '620715294422',
    projectId: 'juno-2ea45',
    authDomain: 'juno-2ea45.firebaseapp.com',
    storageBucket: 'juno-2ea45.firebasestorage.app',
    measurementId: 'G-LLC392ZGP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIn-cvYUzHknoGVjs-BytxsdpARa4nNu8',
    appId: '1:620715294422:android:83b9c144a2afc9fd6e1377',
    messagingSenderId: '620715294422',
    projectId: 'juno-2ea45',
    storageBucket: 'juno-2ea45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBufZ9tH_xygLbDSGzmWbC9rlZAZNOH9vE',
    appId: '1:620715294422:ios:51650fe41356f86d6e1377',
    messagingSenderId: '620715294422',
    projectId: 'juno-2ea45',
    storageBucket: 'juno-2ea45.firebasestorage.app',
    iosBundleId: 'com.juno.junoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBufZ9tH_xygLbDSGzmWbC9rlZAZNOH9vE',
    appId: '1:620715294422:ios:51650fe41356f86d6e1377',
    messagingSenderId: '620715294422',
    projectId: 'juno-2ea45',
    storageBucket: 'juno-2ea45.firebasestorage.app',
    iosBundleId: 'com.juno.junoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrA4TpUuZpIcLq9vkuU_V89dGWmzROznM',
    appId: '1:620715294422:web:1d9ffe748f4496db6e1377',
    messagingSenderId: '620715294422',
    projectId: 'juno-2ea45',
    authDomain: 'juno-2ea45.firebaseapp.com',
    storageBucket: 'juno-2ea45.firebasestorage.app',
    measurementId: 'G-574X7P0GG9',
  );
}
